### PR TITLE
Remove references to ranch_tcp and ranch_ssl.

### PR DESCRIPTION
**Pull request by seancribbs**
Every test using the PB client, especially `pb_security`, should still pass after this change. There are no existing unit tests exercising SSL/TLS.

### CODE REVIEW

**Comment by seancribbs** [comment]
^^ @jaredmorrow @metadave

**Comment by bookshelfdave** [comment]
did ranch handle any other `crypto`, `public_key`, or `ssl` deps/startup that we need to worry about?

otherwise, +1, all tests pass
https://gist.github.com/metadave/7936654

**Comment by seancribbs** [comment]
@metadave Did you run the `pb_security` riak_test? Just trying to cover my bases.

**Comment by bookshelfdave** [comment]
pb_security failure :-( https://gist.github.com/metadave/7945810/raw/eb89a5350195cf222bda4f64fd92dfd029220d0c/gistfile1.txt

**Comment by seancribbs** [comment]
@metadave Did you build Riak and riak_test with R16B02-basho3?

**Comment by bookshelfdave** [comment]
tested w/ R16B02, I'll try R16B02-basho3

**Comment by bookshelfdave** [comment]
pb_security riak_test passes (multiple runs) with R16B02-basho3 
https://gist.github.com/metadave/7947298
+1

**Pull request merged**
