### PR TITLE
Bump webmachine.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by seancribbs** [comment]
Is this waiting on something else? The build gives a version mismatch on meck.

**Comment by cmeiklejohn** [comment]
Waiting on the protobuffs one and a riak_pb retag.  Sorry for the confusion.

**Comment by seancribbs** [comment]
No problem. I'll look at the protobuffs one.

**Comment by cmeiklejohn** [comment]
Obsoleted by https://github.com/basho/riak_api/pull/78.

**Pull request closed without merging**
