### PR TITLE
Develop branch should use 2.1 of riak_pb.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1: 3106bce

This is necessary for RIAK-1481

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
ugh

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
@borshop merge

**Pull request merged**
