### PR TITLE
Fix late registrations: riak_api_pb_server is no longer a gen_server

### PR DESCRIPTION
**Pull request by seancribbs**
Use `gen_fsm:send_all_state_event/2` instead of `gen_server:cast/2`.

### CODE REVIEW

**Comment by seancribbs** [comment]
Fixes 'unrecognized message' bugs found in http://giddyup.basho.com/#/projects/riak/scorecards/60/60-1324-yz_siblings-ubuntu-1004-64/28410/artifacts/382221

**Comment by seancribbs** [comment]
@rzezeski Could you review this, given you originally reported the issue?

**Comment by rzezeski** [comment]
Yea I should be able to check this on my next riak test run.

**Comment by seancribbs** [comment]
Awesome, thanks!

**Comment by rzezeski** [comment]
I no longer see the unrecognized messages and the code looks good. +1 to merge.

**Pull request merged**
