### PR TITLE
Handle the {error, no_type} return from riak_core_bucket.

### LINKED ISSUE #61: riak_core_pb_bucket crashes with function_clause on {error, notype}
```
2014-04-19 15:18:33.273 [error] <0.287.0> Supervisor riak_api_pb_sup had child undefined started with {riak_api_pb_server,start_link,undefined} at <0.4061.0> exit with reason {error,function_clause,[{riak_pb_codec,encode_bucket_props,[{error,no_type},{rpbbucketprops,undefined,undefined,undefined,[],false,[],false,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"src/riak_pb_codec.erl"},{line,232}]},{riak_core_pb_bucket,process,2,[{file,"src/riak_core_pb_bucket.erl"},{line,82}]},{riak_api_pb_server,process_message,...},...]} in context child_terminated
```

### PR DESCRIPTION
**Pull request by seancribbs**
Fixes #61. Update to the `bucket_types` test is forthcoming.

### CODE REVIEW

**Comment by macintux** [comment]
@bowrocker is reviewing

**Comment by bowrocker** [comment]
Added a test to riak_test bucket_types for this change, which passes with this branch:

https://github.com/basho/riak_test/pull/619

https://gist.github.com/bowrocker/6085b380f55703723c03

:1

**Comment by andrewjstone** [comment]
- [x] code review
- [x] https://github.com/basho/riak_test/pull/610 fails without this fix
- [x] https://github.com/basho/riak_test/pull/610 passes with this fix

**Comment by andrewjstone** [comment]
I squashed and rebased your whitespace commit. I hope you don't mind @seancribbs

**Comment by andrewjstone** [comment]
:+1:  ef62bef

**Comment by seancribbs** [comment]
@andrewjstone thanks for squash/rebase

**Comment by seancribbs** [comment]
FYI, still the related riak_coré PR is still pending thanks to test failures.

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
